export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          facebook_id: string;
          name: string;
          email: string | null;
          profile_picture: string | null;
          role: 'admin' | 'manager' | 'editor' | 'member';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facebook_id: string;
          name: string;
          email?: string | null;
          profile_picture?: string | null;
          role?: 'admin' | 'manager' | 'editor' | 'member';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facebook_id?: string;
          name?: string;
          email?: string | null;
          profile_picture?: string | null;
          role?: 'admin' | 'manager' | 'editor' | 'member';
          created_at?: string;
          updated_at?: string;
        };
      };
      facebook_pages: {
        Row: {
          id: string;
          facebook_page_id: string;
          user_id: string;
          name: string;
          category: string | null;
          profile_picture: string | null;
          follower_count: number | null;
          access_token: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          facebook_page_id: string;
          user_id: string;
          name: string;
          category?: string | null;
          profile_picture?: string | null;
          follower_count?: number | null;
          access_token: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          facebook_page_id?: string;
          user_id?: string;
          name?: string;
          category?: string | null;
          profile_picture?: string | null;
          follower_count?: number | null;
          access_token?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          title: string;
          content: string;
          page_id: string;
          created_by: string;
          recipient_type: 'all' | 'active';
          recipient_count: number;
          status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
          scheduled_for: string | null;
          sent_at: string | null;
          delivered_count: number;
          opened_count: number;
          clicked_count: number;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          page_id: string;
          created_by: string;
          recipient_type: 'all' | 'active';
          recipient_count?: number;
          status?: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
          scheduled_for?: string | null;
          sent_at?: string | null;
          delivered_count?: number;
          opened_count?: number;
          clicked_count?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          page_id?: string;
          created_by?: string;
          recipient_type?: 'all' | 'active';
          recipient_count?: number;
          status?: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
          scheduled_for?: string | null;
          sent_at?: string | null;
          delivered_count?: number;
          opened_count?: number;
          clicked_count?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      messenger_conversations: {
        Row: {
          id: string;
          user_id: string;
          page_id: string;
          sender_id: string;
          sender_name: string | null;
          last_message: string | null;
          last_message_time: string;
          conversation_status: 'active' | 'inactive' | 'blocked';
          message_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          page_id: string;
          sender_id: string;
          sender_name?: string | null;
          last_message?: string | null;
          last_message_time: string;
          conversation_status?: 'active' | 'inactive' | 'blocked';
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          page_id?: string;
          sender_id?: string;
          sender_name?: string | null;
          last_message?: string | null;
          last_message_time?: string;
          conversation_status?: 'active' | 'inactive' | 'blocked';
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          user_id: string;
          role: 'admin' | 'manager' | 'editor' | 'member';
          permissions: string[];
          invited_by: string | null;
          joined_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role: 'admin' | 'manager' | 'editor' | 'member';
          permissions?: string[];
          invited_by?: string | null;
          joined_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: 'admin' | 'manager' | 'editor' | 'member';
          permissions?: string[];
          invited_by?: string | null;
          joined_at?: string;
        };
      };
      message_activity: {
        Row: {
          id: string;
          message_id: string;
          activity_type: 'created' | 'scheduled' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'failed';
          description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          activity_type: 'created' | 'scheduled' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'failed';
          description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          message_id?: string;
          activity_type?: 'created' | 'scheduled' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'failed';
          description?: string;
          created_at?: string;
        };
      };
      contact_interaction_events: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          event_type: 'message_sent' | 'message_delivered' | 'message_opened' | 'message_clicked' | 'message_replied' | 'call_initiated' | 'call_completed' | 'meeting_scheduled' | 'meeting_attended';
          event_timestamp: string;
          response_timestamp: string | null;
          response_latency_hours: number | null;
          message_id: string | null;
          channel: 'messenger' | 'email' | 'call' | 'sms' | 'meeting';
          is_outbound: boolean;
          is_success: boolean;
          success_weight: number;
          metadata: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          event_type: 'message_sent' | 'message_delivered' | 'message_opened' | 'message_clicked' | 'message_replied' | 'call_initiated' | 'call_completed' | 'meeting_scheduled' | 'meeting_attended';
          event_timestamp: string;
          response_timestamp?: string | null;
          response_latency_hours?: number | null;
          message_id?: string | null;
          channel?: 'messenger' | 'email' | 'call' | 'sms' | 'meeting';
          is_outbound?: boolean;
          is_success?: boolean;
          success_weight?: number;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          sender_id?: string;
          event_type?: 'message_sent' | 'message_delivered' | 'message_opened' | 'message_clicked' | 'message_replied' | 'call_initiated' | 'call_completed' | 'meeting_scheduled' | 'meeting_attended';
          event_timestamp?: string;
          response_timestamp?: string | null;
          response_latency_hours?: number | null;
          message_id?: string | null;
          channel?: 'messenger' | 'email' | 'call' | 'sms' | 'meeting';
          is_outbound?: boolean;
          is_success?: boolean;
          success_weight?: number;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
      };
      contact_timing_bins: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          hour_of_week: number;
          trials_count: number;
          success_count: number;
          raw_probability: number;
          smoothed_probability: number;
          calibrated_probability: number;
          last_sample: number;
          exploration_count: number;
          last_updated: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          hour_of_week: number;
          trials_count?: number;
          success_count?: number;
          raw_probability?: number;
          smoothed_probability?: number;
          calibrated_probability?: number;
          last_sample?: number;
          exploration_count?: number;
          last_updated?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          sender_id?: string;
          hour_of_week?: number;
          trials_count?: number;
          success_count?: number;
          raw_probability?: number;
          smoothed_probability?: number;
          calibrated_probability?: number;
          last_sample?: number;
          exploration_count?: number;
          last_updated?: string;
          created_at?: string;
        };
      };
      contact_timing_recommendations: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          sender_name: string | null;
          timezone: string;
          timezone_confidence: 'low' | 'medium' | 'high';
          timezone_source: string | null;
          recommended_windows: RecommendedWindow[];
          max_confidence: number;
          recency_score: number;
          priority_score: number;
          composite_score: number;
          last_positive_signal_at: string | null;
          last_contact_attempt_at: string | null;
          total_attempts: number;
          total_successes: number;
          overall_response_rate: number;
          quiet_hours_start: string | null;
          quiet_hours_end: string | null;
          preferred_days: number[] | null;
          daily_attempt_cap: number;
          weekly_attempt_cap: number;
          min_spacing_hours: number;
          is_active: boolean;
          cooldown_until: string | null;
          notes: string | null;
          last_computed_at: string;
          computation_duration_ms: number | null;
          algorithm_version: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          sender_id: string;
          sender_name?: string | null;
          timezone?: string;
          timezone_confidence?: 'low' | 'medium' | 'high';
          timezone_source?: string | null;
          recommended_windows?: RecommendedWindow[];
          max_confidence?: number;
          recency_score?: number;
          priority_score?: number;
          composite_score?: number;
          last_positive_signal_at?: string | null;
          last_contact_attempt_at?: string | null;
          total_attempts?: number;
          total_successes?: number;
          overall_response_rate?: number;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          preferred_days?: number[] | null;
          daily_attempt_cap?: number;
          weekly_attempt_cap?: number;
          min_spacing_hours?: number;
          is_active?: boolean;
          cooldown_until?: string | null;
          notes?: string | null;
          last_computed_at?: string;
          computation_duration_ms?: number | null;
          algorithm_version?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          sender_id?: string;
          sender_name?: string | null;
          timezone?: string;
          timezone_confidence?: 'low' | 'medium' | 'high';
          timezone_source?: string | null;
          recommended_windows?: RecommendedWindow[];
          max_confidence?: number;
          recency_score?: number;
          priority_score?: number;
          composite_score?: number;
          last_positive_signal_at?: string | null;
          last_contact_attempt_at?: string | null;
          total_attempts?: number;
          total_successes?: number;
          overall_response_rate?: number;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          preferred_days?: number[] | null;
          daily_attempt_cap?: number;
          weekly_attempt_cap?: number;
          min_spacing_hours?: number;
          is_active?: boolean;
          cooldown_until?: string | null;
          notes?: string | null;
          last_computed_at?: string;
          computation_duration_ms?: number | null;
          algorithm_version?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      contact_timing_segment_priors: {
        Row: {
          id: string;
          user_id: string;
          segment_type: 'global' | 'industry' | 'role' | 'region' | 'channel';
          segment_value: string;
          hour_of_week: number;
          trials_count: number;
          success_count: number;
          response_rate: number;
          contact_count: number;
          last_updated: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          segment_type: 'global' | 'industry' | 'role' | 'region' | 'channel';
          segment_value?: string;
          hour_of_week: number;
          trials_count?: number;
          success_count?: number;
          response_rate?: number;
          contact_count?: number;
          last_updated?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          segment_type?: 'global' | 'industry' | 'role' | 'region' | 'channel';
          segment_value?: string;
          hour_of_week?: number;
          trials_count?: number;
          success_count?: number;
          response_rate?: number;
          contact_count?: number;
          last_updated?: string;
          created_at?: string;
        };
      };
      contact_timing_config: {
        Row: {
          id: string;
          user_id: string;
          lambda_fast: number;
          lambda_slow: number;
          alpha_prior: number;
          beta_prior: number;
          hierarchical_kappa: number;
          epsilon_exploration: number;
          success_weight_reply: number;
          success_weight_click: number;
          success_weight_open: number;
          survival_gamma: number;
          top_k_windows: number;
          min_spacing_hours: number;
          daily_attempt_cap: number;
          weekly_attempt_cap: number;
          success_window_hours: number;
          w1_confidence: number;
          w2_recency: number;
          w3_priority: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lambda_fast?: number;
          lambda_slow?: number;
          alpha_prior?: number;
          beta_prior?: number;
          hierarchical_kappa?: number;
          epsilon_exploration?: number;
          success_weight_reply?: number;
          success_weight_click?: number;
          success_weight_open?: number;
          survival_gamma?: number;
          top_k_windows?: number;
          min_spacing_hours?: number;
          daily_attempt_cap?: number;
          weekly_attempt_cap?: number;
          success_window_hours?: number;
          w1_confidence?: number;
          w2_recency?: number;
          w3_priority?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lambda_fast?: number;
          lambda_slow?: number;
          alpha_prior?: number;
          beta_prior?: number;
          hierarchical_kappa?: number;
          epsilon_exploration?: number;
          success_weight_reply?: number;
          success_weight_click?: number;
          success_weight_open?: number;
          survival_gamma?: number;
          top_k_windows?: number;
          min_spacing_hours?: number;
          daily_attempt_cap?: number;
          weekly_attempt_cap?: number;
          success_window_hours?: number;
          w1_confidence?: number;
          w2_recency?: number;
          w3_priority?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contact_timing_executions: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          recommendation_id: string | null;
          scheduled_for: string;
          executed_at: string | null;
          window_dow: string | null;
          window_hour: number | null;
          hour_of_week: number | null;
          status: 'scheduled' | 'executed' | 'skipped' | 'failed';
          outcome: 'success' | 'no_response' | 'failed' | 'opted_out' | null;
          response_received_at: string | null;
          response_latency_hours: number | null;
          message_id: string | null;
          channel: string;
          execution_metadata: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          recommendation_id?: string | null;
          scheduled_for: string;
          executed_at?: string | null;
          window_dow?: string | null;
          window_hour?: number | null;
          hour_of_week?: number | null;
          status?: 'scheduled' | 'executed' | 'skipped' | 'failed';
          outcome?: 'success' | 'no_response' | 'failed' | 'opted_out' | null;
          response_received_at?: string | null;
          response_latency_hours?: number | null;
          message_id?: string | null;
          channel?: string;
          execution_metadata?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          recommendation_id?: string | null;
          scheduled_for?: string;
          executed_at?: string | null;
          window_dow?: string | null;
          window_hour?: number | null;
          hour_of_week?: number | null;
          status?: 'scheduled' | 'executed' | 'skipped' | 'failed';
          outcome?: 'success' | 'no_response' | 'failed' | 'opted_out' | null;
          response_received_at?: string | null;
          response_latency_hours?: number | null;
          message_id?: string | null;
          channel?: string;
          execution_metadata?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Supporting types
export interface RecommendedWindow {
  dow: string;
  time: string; // Specific time (e.g., "08:00" or "19:30")
  confidence: number;
  hour_of_week: number;
}

